config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users, only: [:index] do
    resources :books, only: [:index] do
      get 'refresh'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  has_many :follows
  has_many :following_users, through: :follows, source: :user
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :upvotes
  has_many :preferring_users, through: :upvotes, source: :user

  scope :newly_created, -> (last_book) {
    where("books.created_at > ?", last_book.created_at)
  }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :author
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_many :upvotes
  has_many :follows
  has_many :preferred_books, through: :upvotes, source: :book
  has_many :followed_authors, through: :follows, source: :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = current_user
    @books = Feed.new(current_user).retrieve
  end

  def refresh
    populate
    @user = current_user
    @new_books = Feed.new(current_user).refresh(params[:book_id])
    @books = Feed.new(current_user).retrieve.where.not(id: @new_books.ids)

    render 'index'
  end

  private

  def current_user
    User.find(params[:user_id])
  end

  def populate
    new_book = current_user.followed_authors.first.books.create(title: 'New book', published_on: Date.today)    
    Upvote.create(user: current_user, book: new_book)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.erb
<h1>Preferred books of <%= @user.name%></h1>

<%= link_to 'populate and refresh', user_book_refresh_path(@user, @new_books ? @new_books.last : @user.preferred_books.last) %>
<table style="width:100%">
  <tr>
    <th>Title</th>
    <th>Published on</th> 
    <th>Author</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title%></td>
      <td><%= book.published_on%></td>
      <td><%= book.author.name%></td>
    </tr>
  <%end%>
  <% @new_books.each do |book| %>
    <tr style='background-color: #f1f2f2'>
      <td><%= book.title%></td>
      <td><%= book.published_on%></td>
      <td><%= book.author.name%></td>
    </tr>
  <%end if @new_books%>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReedsyChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.erb
<h1>Who are you ?</h1>

<% @users.each do |user| %>
  <%= link_to user.name, user_books_path(user) %>
<%end%>